#!/usr/bin/env python3
"""Render a weekly research proposal and application report as reviewable Markdown."""

from __future__ import annotations

import argparse
import json
from pathlib import Path
from typing import Any


def link_sources(urls: list[str]) -> str:
    return " · ".join(f"[source {index + 1}]({url})" for index, url in enumerate(urls))


def render(proposal: dict[str, Any], report: dict[str, Any] | None = None) -> str:
    report = report or {}
    lines = [
        f"# DeployIndex weekly catalog research — {proposal['research_date']}",
        "",
        proposal["summary"],
        "",
        "## Safety boundary",
        "",
        "This pull request was generated by the weekly discovery workflow. It may add or correct records, but it **never hard-deletes entries and never automatically applies shutdown or archive alerts**. Review source evidence before merging.",
        "",
        "## Findings",
        "",
        f"- New candidates: **{len(proposal.get('new_candidates', []))}**",
        f"- Metadata updates: **{len(proposal.get('updates', []))}**",
        f"- Status alerts requiring review: **{len(proposal.get('status_alerts', []))}**",
        f"- Existing entries re-verified: **{len(proposal.get('checked_active', []))}**",
    ]
    if proposal.get("research_model"):
        lines.append(f"- Research model: `{proposal['research_model']}`")
    if proposal.get("response_id"):
        lines.append(f"- Responses API record: `{proposal['response_id']}`")

    candidates = proposal.get("new_candidates", [])
    if candidates:
        lines += ["", "## Proposed additions", "", "| Entry | Type | Category | Confidence | Evidence |", "|---|---|---|---|---|"]
        for item in candidates:
            lines.append(
                f"| [{item['name']}]({item['url']}) (`{item['slug']}`) | {item['entity_type']} | {item['primary_category']} | {item['confidence']} | {link_sources(item['source_urls'])} |"
            )
            lines.append(f"\n> {item['change_note']}")

    updates = proposal.get("updates", [])
    if updates:
        lines += ["", "## Proposed metadata updates", ""]
        for item in updates:
            changed = []
            patch = item["patch"]
            for field, value in patch.items():
                if field.endswith("_action"):
                    if value != "keep":
                        changed.append(f"`{field}` → `{value}`")
                elif value is not None:
                    changed.append(f"`{field}`")
            lines += [
                f"### `{item['slug']}`",
                "",
                f"Fields: {', '.join(changed) or 'none'}  ",
                f"Confidence: **{item['confidence']}**  ",
                f"Evidence: {link_sources(item['source_urls'])}",
                "",
                item["rationale"],
                "",
            ]

    alerts = proposal.get("status_alerts", [])
    if alerts:
        lines += ["", "## Status alerts — manual decision required", ""]
        for item in alerts:
            effective = f"; effective {item['effective_date']}" if item.get("effective_date") else ""
            lines += [
                f"### `{item['slug']}` → `{item['proposed_status']}` / `{item['proposed_availability']}`{effective}",
                "",
                f"Confidence: **{item['confidence']}**  ",
                f"Evidence: {link_sources(item['source_urls'])}",
                "",
                item["rationale"],
                "",
                "- [ ] Confirm with a first-party shutdown, migration, acquisition, or availability notice.",
                "- [ ] Decide whether the historical page should remain indexed.",
                "- [ ] Apply the status change manually in a follow-up commit when warranted.",
                "",
            ]

    checked = proposal.get("checked_active", [])
    if checked:
        lines += ["", "## Re-verified entries", ""]
        for item in checked:
            lines.append(f"- `{item['slug']}` — {item['note']} ({link_sources(item['source_urls'])})")

    if report:
        lines += [
            "",
            "## Applied by the conservative staging step",
            "",
            f"- Added: {', '.join(f'`{slug}`' for slug in report.get('added', [])) or 'none'}",
            f"- Updated: {', '.join(f'`{slug}`' for slug in report.get('updated', {})) or 'none'}",
            f"- Verification timestamps refreshed: {', '.join(f'`{slug}`' for slug in report.get('verified', [])) or 'none'}",
            f"- Low-confidence findings skipped: **{len(report.get('skipped_low_confidence', []))}**",
            f"- Status alerts intentionally not applied: **{len(report.get('status_alerts_not_applied', []))}**",
        ]

    lines += [
        "",
        "## Required review",
        "",
        "- [ ] Confirm new entries are actual deployment surfaces rather than adjacent SaaS products.",
        "- [ ] Confirm provider/product/project identity and parent relationships.",
        "- [ ] Open the cited primary sources and check that the paraphrased claims are supported.",
        "- [ ] Confirm no duplicate product, predecessor, rebrand, or canonical domain already exists.",
        "- [ ] Run `make test` and inspect the generated site locally.",
        "",
    ]
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("proposal", type=Path)
    parser.add_argument("--report", type=Path)
    parser.add_argument("--output", type=Path)
    args = parser.parse_args()
    proposal = json.loads(args.proposal.read_text(encoding="utf-8"))
    report = json.loads(args.report.read_text(encoding="utf-8")) if args.report else None
    output = render(proposal, report)
    if args.output:
        args.output.write_text(output + "\n", encoding="utf-8")
    else:
        print(output)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
